### ISSUE TITLE
Group milestone 1a

### ISSUE THREAD

**Issue by Qspace** [ThreeRangers/Flea#1]
We have already complete these following tasks (except for the survey as we still need to collect the feedbacks):
### Create your organization and project
- [x] Create an organization on Github
- [x] Add each team member in your group to the organization
- [x] Generate a new Xcode project for your group.
- [x] Push the repository to your new project organization.
- [x] Sketch our functional user stories
### Add a README to your project repo with the following elements:
- [x] Paragraph that describes your app and what it does
- [x] Required (core) user stories for your app in a bulleted list
- [x] Optional (nice to have) user stories listed separately
### Research:
- [ ] Ask 3 different people for feedback on your idea. Write down their responses and create a document in your GitHub repository with their answers. (still missing the answers)
- Link to the survey: [Travel Planning App Survey](http://www.surveygizmo.com/s3/2479321/Travel-Planning-App-Survey)

/cc @coderschoolreview @minhcasi @Qspace  @datnguyen-personal
